feat: Menus
uni-tj/robo-arena pull request #44
Opened 2024-07-07 18:47 UTC by JulesOxe

Introduces the main menu and the settings menu, as well as the function to create additional menus generically.

- Generic buttons:

    - can be positioned using a relative position
    - change their appearance when you move the mouse over them
    - execute a function when they are clicked

- Generic text fields:

    - can be positioned relative to each other
    - adjustable font size
    - currently still a standard font
 
Multiple buttons and text fields can be managed by a menu class whose object represents a menu page. Each menu takes care of its own rendering and informs its buttons about the mouse position.
Menu backgrounds can be designed with a colour gradient.
The position of the menu elements is specified as a relative percentage. The size and position of the elements adapts dynamically to the screen size.

There are now different subclasses of the renderer that have special rendering functions for their purposes. For example, for the game or for the menus.

2024-07-07 18:50 UTC, JulesOxe commented
@p-98 Help needed!

1. i need an opinion on the best way to integrate my different files into the existing project structure. Currently all files are located in a subfolder of the client.

2. i have not been able to integrate the quit function correctly. It is currently not possible to quit in the menu screen. Can someone please help me with the reason for this?

2024-07-09 22:28 UTC, p-98 requested changes
Okay thats quite a batch, but nice work and I will give my best to give you some feedback.

Here are some things I noted:
- make `Renderable.dimensions_px` and `.position_px` cached properties. This reduces mutability and mental overhead.
- Remove `Menu.background_colors` and instead pass the values to `create_background_texture` since they are needed only there. Also make this method return the texture for less side effect. You could even make it a static method, though thats just a thought.
- Rename `Button.render_button` to `Button.render` and the same for texts as this makes for predictable method names. To make this a valid override of `Renderable.render`, `texture_size` might be set as object property on `Renderable`.
- Rename `Menu.menu_loop` to `Menu.loop` for the same reason.
- Optionally rename `Menu.deactivate` to `Menu.close` (and the according property) as I first confused the name with `stop`
- Not sure why `load_texture` scales the textures as I thought they should only be scaled on render?
- Most things like `buttons` can defined outside the constructor of `SettingsMenu` (probably also applicable to `MainMenu`). This makes the function shorter, loads the textures only once on game load and reduces mental overhead because they are kinda constants.
- Move `os.path.join(os.path.dirname(__file__), "recources/graphics/..."))` into a simple helper function to reduce boilerplate.

Since this stuff is only needed on the client, the `menu` subdirectory sounds like a valid option. `settings.yml` should be in the project root though (@weiserhase is this even possible with our package setup?) and `resources` should probably be in one directory under `shared` to keep all the textures in one place.

For graceful quit you have to catch `pygame.QUIT` event, similar to `client.py:214` and then dispatch the event and catch it in the `Client` like the `GameState` event. But I can do that if you like.

The above might look like much, but I think your work is a good place to start, as it was quite fuzzy what should even be the outcome.

PS: the textures look nice :)

2024-07-13 11:14 UTC, JulesOxe commented
@p-98 your suggested changes have been implemented and the branch is now up to date with main :)

2024-08-05 07:58 UTC, p-98 approved these changes

2024-08-05 13:54 UTC, merged